### PR TITLE
Revert to using toCanonical() resource changed checking

### LINKED ISSUE #1998: Incorrect message "Resource has unsaved changes. Are you sure you want to close?" displaying
Closing a saved description in the University of Washington's resource templates results in the message "Resource has unsaved changes. Are you sure you want to close?" when there are in fact no unsaved changes. This happens with both new descriptions and after editing previously-saved descriptions and re-saving.

image

### PR DESCRIPTION
**Pull request by jermnelson**
Fixes #1998

### CODE REVIEW

File: src/actionCreators/resources.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ import _ from 'lodash'
 export const update = (resourceKey, currentUser, errorKey) => (dispatch, getState) => {
   const state = getState()
   const uri = findResourceURI(state, resourceKey)
-  const rdf = new GraphBuilder(state.selectorReducer.entities.resources[resourceKey], state.selectorReducer.entities.resourceTemplates).toTurtle()
+  const rdf = new GraphBuilder(state.selectorReducer.entities.resources[resourceKey], state.selectorReducer.entities.resourceTemplates).graph.toCanonical()
```
Comment (mjgiarlo) [inline src/actionCreators/resources.js]: Maybe you want two variables here: one to hold the turtle (for persisting) on line 30 and one to hold the n-triples (for checksumming) on line 31?

Comment (jermnelson) [reply src/actionCreators/resources.js]: Thanks, good catch! Just pushed a commit that use the `GraphBuilder` instance to produce both Turtle and n-triples serializations as needed.
