### PR TITLE
Make property tooltips hide when elsewhere is clicked

### LINKED ISSUE #2539: Tooltip should close when user clicks away
**Describe the bug**
What went wrong? What did you expect to happen?

The **i** button doesn't disappear after it is clicked. I was expecting that it would dissapear after I navigate away from the **i** message.

image

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)

If you don't click the **i** again to make it close, the little info box will persist forever!

- What environment are you in? (stage or production)
stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Mac Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
_Monograph Work (BF2) Un-Nested

**Please include a screenshot**

Screen Shot 2020-09-25 at 12 45 27 PM

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #2539

## Why was this change made?

To make tooltips behave per user expectations.

## How was this change tested?

CI and local browser.

**NOTE**: I fought with RTL/Jest for 1-2 hours and could not get the commented-out test line to pass. That line is the most important line to testing that the clicks work properly. Advice or code are most welcome.

## Which documentation and/or configurations were updated?

None

### CODE REVIEW

File: src/components/editor/property/PropertyLabelInfoTooltip.jsx [hunk 1]
```diff
@@ -14,15 +14,20 @@ const PropertyLabelInfoTooltip = (props) => {
...
-          data-container="body"
-          title={props.propertyTemplate.label}
-          data-content={props.propertyTemplate.remark}
-          key={key}
-          id={key}>
+    <a href="#"
+       className="tooltip-heading"
+       tabIndex="0"
+       data-toggle="popover"
+       data-trigger="focus"
```
Comment (mjgiarlo) [inline src/components/editor/property/PropertyLabelInfoTooltip.jsx:21]: This is the line that does the magic, but it only works inside an `<a>` element, not a `<span>` or `<button>` element.

File: src/styles/main.scss [hunk 2]
```diff
@@ -92,6 +93,11 @@ $primary-disabled: lighten( map-get($theme-colors,"secondary"), 20% );
   border-style: dashed;
 }
 
+a.tooltip-heading {
```
Comment (mjgiarlo) [inline src/styles/main.scss:96]: Retain look & feel after changing `<span>` to `<a>`

**Review by justinlittman — APPROVED** [review]
For what it is worth, this is the sort of case where a small Cypress test might be appropriate. However, no need to hold up this fix.

**Comment by mjgiarlo** [comment]
@justinlittman :speech_balloon: 
> For what it is worth, this is the sort of case where a small Cypress test might be appropriate. However, no need to hold up this fix.

Great idea. Here you go: https://github.com/LD4P/sinopia_editor/pull/2547
