### PR TITLE
Removes property template as InputLiteral prop. Validates resource te…

### LINKED ISSUE #765: when a resource template has a property template with the same property URI as the preceding property template, the placeholder text for the second field incorrectly uses the property label for the first field
example template on stage showing this:
test:repeated:tooltips
there's one Resource Template with 2 Property Templates;
both use propertyURI http://id.loc.gov/ontologies/bibframe/geographicCoverage
(yes, there are use cases for this)
the first field has propertyLabel "Geographic Coverage 1"
the second field has propertyLabel "Geographic Coverage 2"
yet the light-colored placeholder text (the text in the entry box) says "Geographic Coverage 1" for both fields
Screen Shot 2019-06-18 at 2 15 07 PM
these fields are both literals. I also tested with the first field being a lookup and the second a literal, both with same propertyURI, and had the same problem

NOTE: an easy way to "fix" this might be to remove placeholder text altogether. There is no requirement for it that I know of.

### LINKED ISSUE #849: InputLiteral component should retrieve propertyTemplate from redux state via reduxPath
analogous to issue #694 (for InputListLOC) and to 5a0090af  

The InputLiteral component currently uses a combination of propertyTemplate passed in as prop and redux state.  propertyTemplate should be derived from the reduxPath using the stored Resource Templates in the entities object in the Redux state.

### PR DESCRIPTION
**Pull request by justinlittman**
…mplates for repeated property URIs.

closes #765. closes #849.

### CODE REVIEW

File: src/actionCreators.js [hunk 1]
```diff
@@ -31,9 +31,33 @@ export const fetchRootResourceTemplate = resourceTemplateId => (dispatch) => {
...
+    } else {
+      dispatch(rootResourceTemplateLoaded(resourceTemplate))
+    }
   }).catch((err) => {
     console.error(err)
     dispatch(retrieveError(resourceTemplateId))
   })
 }
+
+export const validateResourceTemplate = (resourceTemplate) => {
```
Comment (jcoyne) [inline src/actionCreators.js]: Can you move this to a different file, because it is not an actionCreator (it does not return a function that takes dispatch and optionally getState)

File: src/reducers/index.js [hunk 2]
```diff
@@ -99,10 +99,18 @@ export const resourceTemplateLoaded = (state, action) => {
...
+  const resourceTemplateId = action.payload.resourceTemplateId
+  const reason = action.payload.reason
   const newState = { ...state }
 
-  newState.editor.serverError = `There was a problem retrieving ${resourceTemplateId}`
+  let serverError = `There was a problem retrieving ${resourceTemplateId}`
+  if (reason) {
+    serverError += `: ${reason}`
+  } else {
+    serverError += '.'
```
Comment (ndushay) [inline src/reducers/index.js]: would it make sense to use something akin to the old verbiage here?  "Sinopia server may be offline or have no resource templates to display" ?

Comment (ndushay) [reply src/reducers/index.js]: Also, vis-a-vis this morning's conversation ... a test for this else branch might be appropriate ...

File: src/actionCreators.js (hunk 1 above)
Comment (justinlittman) [reply src/actionCreators.js]: Done.

[the remark this answers is not in the document]
Comment (justinlittman) [reply src/actionCreators.js]: Add comment docs for the method.

Don't which whether null or undefined or other is idiomatic js.

File: src/reducers/index.js (hunk 2 above)
Comment (justinlittman) [reply src/reducers/index.js]: Added tests.

The old verbiage was sometimes wrong. The reducers would specify an error message and this would override and display a different error message.

File: src/ResourceTemplateValidator.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
+// Copyright 2019 Stanford University see LICENSE for license
+
+/**
+ * Validates a resource template.
+ * Validation checks that does not contain repeated property templates.
+ * @param {<object>} resource template to validate
```
Comment (jcoyne) [inline src/ResourceTemplateValidator.js]: Add the parameter name here. I believe the convention for jsdoc is to use `{Object}` (capitalized, no `<>`)

File: src/ResourceTemplateValidator.js [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+ * @return {<string> or null} reasons that validation failed if invalid otherwise null if valid
```
Comment (jcoyne) [inline src/ResourceTemplateValidator.js]: Multiple types should be written as `{(string|null)}`

File: src/reducers/index.js (hunk 2 above)
Comment (ndushay) [reply src/reducers/index.js]: ja, agree and appreciate new logic.  I cleverly changed the old wording to "may" - like, if you don't have a reason, this MIGHT be why.  But not as important as the test - thanks for that.
