### PR TITLE
Correctly handles nested properties that are mandatory and have defau…

### LINKED ISSUE #1022: Nested defaults not added to redux state
Steps to reproduce:
1. Open a new Bibframe instance.
2. Instance the redux state.

Expected result:
`resource > resourceTemplate:bf2:Monograph:Instance >http://id.loc.gov/ontologies/bibframe/itemPortion > <key> > resourceTemplate:bf2:Identifiers:Barcode > http://www.w3.org/1999/02/22-rdf-syntax-ns#value > items` should include the default _12345_.

Actual result:
State is only `resource > resourceTemplate:bf2:Monograph:Instance >http://id.loc.gov/ontologies/bibframe/itemPortion > <key> > resourceTemplate:bf2:Identifiers:Barcode`.

### PR DESCRIPTION
**Pull request by justinlittman**
…lts.

closes #1022

### CODE REVIEW

**Comment by justinlittman** [comment]
Here is a nested property for a resource that is mandatory and has defaults:

File: src/actionCreators/resources.js [hunk 1]
```diff
@@ -136,46 +137,63 @@ const stubResourceProperties = async (resourceTemplateId, existingResourceTempla
...
+
+        if (newResource[propertyTemplate.propertyURI] === undefined) {
+          newResource[propertyTemplate.propertyURI] = {}
+        }
+        // For each value template
+        // Since these are promises, using Promise.all for https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop
+        await Promise.all(
+          propertyTemplate.valueConstraint.valueTemplateRefs.map(async (resourceTemplateId) => {
+            const nestedResourceTemplatePromise = fetchResourceTemplate(resourceTemplateId, dispatch)
+            // See if there is alread a <key> > <resource template id> for this resource template id
```
Comment (jermnelson) [inline src/actionCreators/resources.js]: misspelling, should be `already`

Comment (justinlittman) [reply src/actionCreators/resources.js]: Fixed @jermnelson
