### PR TITLE
Fixes prompt when toggling help.

### LINKED ISSUE #1172: don't warn of unsaved changes when opening Help menu
the new feature to warn user of unsaved changes when they try to leave a RT is great (https://github.com/LD4P/sinopia_editor/commit/d75f1d2d57fdec4d1a22e20e4661c5eb4892ff4f) but now when I'm cataloging, and I need to see the Help menu and click Help & Resources, it warns me "Resource has unsaved changes. Are you sure you want to leave?" and if I say OK so I can see the Help menu, my unsaved changes are still there, and when I close the Help menu, it warns me again, and if I say ok, my unsaved changes are still there.

When you click on Help & Resources you aren't leaving the current Editing session so don't warn of unsaved data.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1172

### CODE REVIEW

File: src/components/App.jsx [hunk 1]
```diff
@@ -74,6 +66,7 @@ App.propTypes = {
   handleOffsetMenu: PropTypes.func,
   hasResource: PropTypes.bool,
   fetchResourceTemplateSummaries: PropTypes.func,
+  isMenuOpened: PropTypes.bool,
```
Comment (jcoyne) [inline src/components/App.jsx]: Is this needed?

Comment (justinlittman) [reply src/components/App.jsx]: Nope. Removed.
