### PR TITLE
CI build includes eslint, which will fail on errors or additional warnings

### LINKED ISSUE #26: CI runs linter
We want CI to:

- run eslint. <-- fail for problems
- do grunt build. <-- fail for problems
- have tests that do something. <-- fail for problems
    - with code coverage. <-- fail for reducing coverage (see #14)
depends on #27

### LINKED ISSUE #27: linter runs cleanly
- is there a way to generate a TODO list so it can ignore existing problems, e.g. in static folder (so we don't diverge from upstream)
- is there an autocorrect we can use for the files of interest (e.g. bfe)

See https://github.com/LD4P/sinopia_profile_editor/pull/42

we can use `.eslintrc` to configure rules so build fails on what WE consider to be egregious errors and `.eslintignore` to ignore upstream js.

### PR DESCRIPTION
**Pull request by ndushay**
Adds eslint and hooks it up with CI build.  It would be good for both @jgreben and @jermnelson to review.

We have to start somewhere. This is a pretty bad place to start ... but it is a way to have our CI builds fail if we have an eslint error, or if the warning count goes up.

image

As we start refactoring and changing code, we'll need to adjust the max-threshold for eslint script in package.json:

image

I felt a few linting errors were worth keeping as errors (not warnings), so I have some small tweaks to files to address these errors from linting.

595070d, the commit moving express to be a regular dependency, not a devDependency *seems* right - we need express to actually run the javascript for a user, no?  "Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications." (http://expressjs.com/).   Kirk may do things differently ...  but the real question is ... what will our users need (in AWS?)

Happy to squash commits, etc.

Closes #27 
Closes #26

### CODE REVIEW

**Comment by jermnelson** [comment]
Looks good to me.  We will be using Express for routing to the new components in the Sinopia Editor so moving it to a regular dependency is needed anyway.

**Comment by jermnelson** [comment]
If we can squash some of these commits, I'm ready to merge. @jgreben any thoughts?

File: src/bfelookups.js [hunk 1]
```diff
@@ -110,68 +110,68 @@ bfe.define('src/lookups/lcnames', ['require', 'exports', 'module', 'src/lookups/
...
+
     exports.getResource = function (subjecturi, property, selected, process) {
       var triples = [];
-  
+
       var triple = {};
       triple.s = subjecturi;
       triple.p = property.propertyURI;
-      selected.uri = selected.uri;
+      // selected.uri = selected.uri;  // FIXME: I *think* this line is useless but feel too green to remove it
```
Comment (ndushay) [inline src/bfelookups.js]: is there any reason to keep this line?

Comment (jgreben) [reply src/bfelookups.js]: I think that self-referential line can be totally deleted. It does absolutely nothing. If you want to push another commit to remove it that would be ok with me.

**Comment by jgreben** [comment]
@jermnelson I'm ok with having a commit list remain on the PR as long as the commits signify atomic functional changes. I usually squash commits when they are of the nature of "FU" and the like (things that didn't really end up getting changed but were temporary or experiments). This PR is a good example of a helpful commit history with atomic functional changes. But I'll go with whatever practice you all want to do as far as squashing commits.

**Comment by jermnelson** [comment]
Merging w/current commit history.
