### PR TITLE
Handles missing valueConstraint and valueTemplateRef in PropertyTemplateOutline

### LINKED ISSUE #509: Clicking the plus to expand a property with a nested resource does not work
receiving console error `TypeError: undefined is not an object (evaluating 'e.map')`

Jeremy believes #493 (merged PR) may solve this

### PR DESCRIPTION
**Pull request by jermnelson**
Adds check for missing valueConstraint and valueConstraint.valueTemplateRefs when user clicks on the plus.

Fixes #509

Todo:
- [x] Test for specific Resource Templates that have propertyTemplates missing `valueConstraint` and `valueConstraint.valueTemplateRefs`

### CODE REVIEW

File: src/components/editor/PropertyTemplateOutline.jsx [hunk 1]
```diff
@@ -180,8 +180,13 @@ export class PropertyTemplateOutline extends Component {
   handleClick = (property) => (event) => {
     event.preventDefault()
     let newOutput = this.state.output
-
-    this.fulfillRTPromises(this.resourceTemplatePromises(property.valueConstraint.valueTemplateRefs))
+    const templateRefList = []
+    if(hasValueTemplateRef(property)) {
+      property.valueConstraint.valueTemplateRefs.map((row) => {
```
Comment (mjgiarlo) [inline src/components/editor/PropertyTemplateOutline.jsx]: I'm a bit confused about what this is doing. Is the intent of this PR to add a check before sending a value to `this.resourceTemplatePromises()`?

Is this code essentially creating a new variable to hold an exact copy of an array? If so, I'm not sure `map` is the clearest solution unless there is a function you want to apply to every member of the array. The intent would be clearer, in my judgment, if you simplified this to:

```javascript
const templateRefList = hasValueTemplateRef(property) ? property.valueConstraint.valueTemplateRefs : []
```

Would that work?

Comment (mjgiarlo) [reply src/components/editor/PropertyTemplateOutline.jsx]: Or, if you add the safe navigation/"Elvis"/optional chaining feature via babel, you can simplify this further to:

```javascript
const templateRefList = property?.valueConstraint?.valueTemplateRefs || []
```

Comment (jermnelson) [reply src/components/editor/PropertyTemplateOutline.jsx]: Thanks! You're right that using `map` over-complicates the `templateRefList` variable setting; I need to read-up on the babel chaining feature you mention but I went ahead and pushed up your first suggestion.
