### PR TITLE
Fixes reduxPath building and corrects GraphBuilder assumption about n…

### LINKED ISSUE #648: Unable to add title to a work
From: https://github.com/LD4P/sinopia_editor/pull/619#issuecomment-499253411

In local testing, I'm getting an error.

Steps to reproduce:
1. Fill out a Bibframe Instance as shown below.
Screen Shot 2019-06-05 at 4 56 14 PM
2. Hit enter.

Results in:
Screen Shot 2019-06-05 at 4 59 06 PM

### PR DESCRIPTION
**Pull request by justinlittman**
…ested resources.

closes #648

### CODE REVIEW

File: src/GraphBuilder.js [hunk 1]
```diff
@@ -49,17 +49,15 @@ export default class GraphBuilder {
...
    */
   buildTriplesForNestedObject(baseURI, value) {
     // Is there ever more than one base node?
-    for (const key in value) {
-      Object.keys(value[key]).forEach((predicateListKey) => {
-        // we don't have a resourceURI to send as the second argument in the propertyTemplates yet.
-        this.buildTriplesForNode(baseURI, null, value[key][predicateListKey])
-      })
-    }
+    Object.keys(value).forEach((rtId) => {
```
Comment (jermnelson) [inline src/GraphBuilder.js]: Small suggestion, you may be able to use `Object.values(value).forEach((rt) => {` and then on line 59, you could just pass in resourceTemplate directly as `rt`.
