### PR TITLE
Missing templates

### LINKED ISSUE #496: PropertyTemplateOutline, ResourceTemplateForm False Positive Tests Clean-up
Remove  or refactor the following **PropertyTemplateOutline.test.js** tests:

All use an approach that is a failed attempted to 'inject' info to an inner method -- attempting to mimic the promises for a particular property template, I believe

#### PropertyTemplateOutline.test.js

- [clicking removes collapsed state](https://github.com/LD4P/sinopia_editor/blob/af0f81ecfad3534ebec3e9cb1484a421f8182a4f/__tests__/components/editor/PropertyTemplateOutline.test.js#L294)
    - "collapsed" isn't a state, it's a prop.  Maybe it should be a state
    - in order to examine STATE after simulate, you must do a fresh "find" from the root component (https://github.com/airbnb/enzyme/issues/1229#issuecomment-462496246)
    - I believe for this to work, mockHandleCollapsed has to mock the implementation ... which leads me to believe that this should be an integration test

- [handles "Add" button click](https://github.com/LD4P/sinopia_editor/blob/af0f81ecfad3534ebec3e9cb1484a421f8182a4f/__tests__/components/editor/PropertyTemplateOutline.test.js#L304)
    - wrapper has OutlineHeader but no PropertyActionButtons, no PropertyTypeRow
    - it needs to be expanded first?  implying an integration test

- [handles "Mint URI" button click](https://github.com/LD4P/sinopia_editor/blob/af0f81ecfad3534ebec3e9cb1484a421f8182a4f/__tests__/components/editor/PropertyTemplateOutline.test.js#L320)
    - wrapper has OutlineHeader but no PropertyActionButtons, no PropertyTypeRow
    - it needs to be expanded first?  implying an integration test

#### ResourceTemplateForm.test.js

- 'renders a lookup component'
- 'renders a list component'
- 'renders InputLiteral nested component (b/c we have a property of type "literal")'
- 'renders error alert box'

### LINKED ISSUE #517: fix message given when trying to open RT that points to an RT that Trellis doesn't know about
When you try to us (open for cataloging) a RT that points to another RT (property template with type = resource), and Trellis doesn't know about the referenced RT, you get a message like:

"There are missing resource templates required by resource template: http://id.loc.gov/ontologies/bibframe/Work.
Make sure all referenced templates in property template are uploaded first"

It would be very helpful to user if it could tell you the *name of the referenced RT that is missing* (instead of telling you the class of the resource template that is pointing to the missing ones).

so instead of:
"There are missing resource templates required by resource template: http://id.loc.gov/ontologies/bibframe/Work..."

the message would be
"This Resource Template requires the following resource templates, which are not yet in Sinopia: [then list the IDs of the missing Resource Templates]"

### PR DESCRIPTION
**Pull request by jgreben**
Fixes #517 
Fixes #496 for ResourceTemplateFormTest

- Collect ids from resource templates that could not be fetched from server and display them in error message:

Screen Shot 2019-05-14 at 4 19 47 PM

- Fix false positives in ResourceTemplateForm tests and test for missing template message

- There was a function that was needed to be used in three different components to get the resource name out of a URI (everything after the last `/`). Switch to using a one-liner instead of repeating that function (or creating a global function)

### CODE REVIEW

File: src/components/editor/ResourceTemplateForm.jsx [hunk 1]
```diff
@@ -222,7 +226,9 @@ export class ResourceTemplateForm extends Component {
     const errMessage = <div className="alert alert-warning">
       There are missing resource templates required by resource template: <strong>{this.props.resourceTemplate.resourceURI}</strong>.
       <br />
-      Make sure all referenced templates in property template are uploaded first
+      Make sure all referenced templates in property template are uploaded first. Missing templates:
```
Comment (ndushay) [inline src/components/editor/ResourceTemplateForm.jsx]: should we say Please?

File: src/components/editor/ResourceTemplateForm.jsx [hunk 2]
```diff
@@ -85,7 +83,13 @@ export class ResourceTemplateForm extends Component {
 
   resourceTemplatePromises = async (templateRefs) => {
     return Promise.all(templateRefs.map(rtId =>
-      getResourceTemplate(rtId)
+      getResourceTemplate(rtId).catch(err => {
+        const errId = decodeURIComponent(/[^/]*$/.exec(err.url)[0])
```
Comment (ndushay) [inline src/components/editor/ResourceTemplateForm.jsx]: while I laud the one-liner, I find this obtuse at best and would not say it passes the "inebriated coder" test.

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 3]
```diff
@@ -13,7 +13,7 @@ describe('<ResourceTemplateForm /> functional testing', () => {
     rtId={'resource:schema:Name'}
     resourceTemplate={ basicRt } />)
 
- const testId = jest.spyOn(shortid, 'generate').mockReturnValue('abcd45')
+ jest.spyOn(shortid, 'generate').mockReturnValue('abcd45')
```
Comment (mjgiarlo) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: If I understand correctly, you are using `jest.spyOn()` here not as a spy but as a stub. Given that, I wonder whether you would consider using `jest.mock()` instead.

Comment (mjgiarlo) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: If I understand correctly, you are using jest.spyOn() here not as a spy but as a stub. Given that, I wonder whether you would consider using jest.mock() instead.

File: src/components/editor/ResourceTemplateForm.jsx [hunk 4]
```diff
@@ -85,7 +83,13 @@ export class ResourceTemplateForm extends Component {
...
+        this.setState({tempErrorUrl: errId})
```
Comment (mjgiarlo) [inline src/components/editor/ResourceTemplateForm.jsx]: I have seen this pattern used elsewhere in the editor and I'm a bit puzzled. As far as I can tell, the only code that looks for and uses `tempErrorUrl` in state is two lines beneath. Which makes me wonder: what do we get out of injecting this into application state? In other words, how is this code different from:

```javascript
const joinedErrorUrls = this.state.templateErrors.slice(0)
joinedErrorUrls.push(errId)
this.setState({templateErrors: joinedErrorUrls})
```

:question:

File: src/components/editor/SinopiaResourceTemplates.jsx [hunk 5]
```diff
@@ -30,7 +30,7 @@ class SinopiaResourceTemplates extends Component {
 
       await this.fulfillGroupPromise(groupPromise).then(async () => {
         this.state.groupData.map(group => {
-          const groupName = this.resourceToName(group)
+          const groupName = /[^/]*$/.exec(group)[0]
```
Comment (mjgiarlo) [inline src/components/editor/SinopiaResourceTemplates.jsx]: I'm OK with moving from a string parsing strategy to a regex matching one, but I wonder whether we should combine strategies here and put the regex strategy **inside** the implementation of `resourceToName` so we don't have an identical regex duplicated several times throughout the code. That will make it less tedious to change later and less error-prone.

File: src/components/editor/SinopiaResourceTemplates.jsx [hunk 6]
```diff
@@ -73,14 +73,9 @@ class SinopiaResourceTemplates extends Component {
   }
 
   groupDataPromise = (groupName, name) => new Promise(async (resolve) => {
-    // await resolve(instance.getResourceWithHttpInfo(groupName, name, { acceptEncoding: 'application/json' }))
```
Comment (mjgiarlo) [inline src/components/editor/SinopiaResourceTemplates.jsx]: Yay for cruft removal!

File: src/components/editor/SinopiaResourceTemplates.jsx [hunk 7]
```diff
@@ -73,14 +73,9 @@ class SinopiaResourceTemplates extends Component {
...
     await resolve(getResourceTemplate(name, groupName))
   })
 
-  resourceToName = (resource) => {
```
Comment (mjgiarlo) [inline src/components/editor/SinopiaResourceTemplates.jsx]: Not a fan of removing this method per the above comment. Also don't love that we have this same method defined in multiple components. Combined with my above related comment, what this says to me is that we ought to have `resourceToName` implemented elsewhere (in some utilities class?) and that both the `SinopiaResourceTemplates` and `UpdateResourceModal` components should import that function. **And** I'm fully on board with replacing the implementation so that it uses a regex instead of substrings.

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> 
> Also, the tests are a no-go; I believe we still have false positives in the affected test file.

This is a concern of mine as well. Can you confirm that you can tweak the expected values in these tests to make them fail?

**Comment by jgreben** [comment]
The issue has changed to loading a profile with missing RTs instead of messaging. Closing PR for now, but please leave branch up for the time being.

**Comment by jgreben** [comment]
After discussing with Michelle, this is the right issue and solution.

File: __tests__/components/editor/ResourceTemplateForm.test.js (hunk 3 above)
Comment (jgreben) [reply __tests__/components/editor/ResourceTemplateForm.test.js]: I couldn't find a way to make it work with just `jest.mock()` but the unused const testId was bothering me. I found a different solution which is:
```
const shortid = require('shortid')
 shortid.generate = jest.fn().mockReturnValue('abcd45')
``` 
Do you think this is better?

File: src/components/editor/ResourceTemplateForm.jsx (hunk 1 above)
Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: I suppose...

File: src/components/editor/ResourceTemplateForm.jsx (hunk 2 above)
Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: So given @mjgiarlo comments below I'm not sure if I should use regex in an imported "utilities" function. I ended up not doing that and used substring instead.

File: src/components/editor/SinopiaResourceTemplates.jsx (hunk 5 above)
Comment (jgreben) [reply src/components/editor/SinopiaResourceTemplates.jsx]: I ended up using substring inside an imported utilities function.

File: src/components/editor/SinopiaResourceTemplates.jsx (hunk 7 above)
Comment (jgreben) [reply src/components/editor/SinopiaResourceTemplates.jsx]: see comments above

File: src/components/editor/ResourceTemplateForm.jsx (hunk 4 above)
Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: That works fine in this case and I fixed it up. I'd have to take a second look at the other instances where I used this pattern. I think here I was blindly following the same pattern I used elsewhere and didn't need to, but I think maybe elsewhere it was used for a reason (maybe because of updating state or awaiting promises). I remember struggling with getting the array in question populated correctly and that pattern is what ended up working for me. In any case, It's definitely work taking a second look at those, and you may already be refactoring the components where those patterns were anyway.

File: __tests__/components/editor/ResourceTemplateForm.test.js (hunk 3 above)
Comment (mjgiarlo) [reply __tests__/components/editor/ResourceTemplateForm.test.js]: @jgreben Yep! That's even better. How would you feel about using `import ... from` instead of `const ... require()`? It looks like we do use both in the editor. Looks like we use import nearly 400 times and we use require 45 times, so we're inching closer to consistency here. This is minor, admittedly.

File: src/components/editor/SinopiaResourceTemplates.jsx (hunk 5 above)
Comment (mjgiarlo) [reply src/components/editor/SinopiaResourceTemplates.jsx]: WFM! Thanks.

File: src/components/editor/SinopiaResourceTemplates.jsx (hunk 7 above)
Comment (mjgiarlo) [reply src/components/editor/SinopiaResourceTemplates.jsx]: :man_dancing:

**Comment by jgreben** [comment]
> @ndushay 💬
> 
> > Also, the tests are a no-go; I believe we still have false positives in the affected test file.
> 
> This is a concern of mine as well. @jgreben Can you confirm that you can tweak the expected values in these tests to make them fail?

I was able to confirm that by changing the various expected values in the test, I could make them fail.

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 8]
```diff
@@ -148,134 +93,144 @@ const responseBody = [{
...
-      resourceTemplate = {rtTest}
-      handleGenerateRDF = {mockHandleGenerateLD}
-      literals = {lits}
-      lookups = {lups}
-      rtId = {"resourceTemplate:bf2:Monograph:Instance"}
-      parentResourceTemplate = {"resourceTemplate:bf2:Monograph:Instance"}
-      generateLD = { ld }
-    />
-  )
+  const mockAsyncCall = (index) => {
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: thanks for the rename - I find it much clearer.

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 9]
```diff
@@ -53,63 +52,9 @@ describe('<ResourceTemplateForm /> functional testing', () => {
         "abcd45",
         "resourceTemplate:bf2:Note"])
     })
-
   })
 })
 
-const rtProps = {
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: i love that you moved these constants down to where they are actually used.

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 10]
```diff
@@ -148,134 +93,144 @@ const responseBody = [{
...
-    },
-    {
-      "@id": "n3-8",
-      "@type": "http://id.loc.gov/ontologies/bibframe/Note",
-      "http://www.w3.org/2000/01/rdf-schema#label": "NOTE"
-    }
-  ]
-}
-
 const rtTest = { resourceURI: "http://id.loc.gov/ontologies/bibframe/Work" }
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: I can live w it as is, but .... "rtTest" ?   what is this?  A resource template missing most of the required data?

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 11]
```diff
@@ -148,134 +93,144 @@ const responseBody = [{
...
+                "urn:ld4p:qa:names:person"
+              ]
+            }
+          }
+        ]
+      }
+
+      const wrapper = shallow(<ResourceTemplateForm {...rtProps} resourceTemplate = {rtTest}/>)
+
+      expect.assertions(2)
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: 👍

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 12]
```diff
@@ -305,31 +260,60 @@ describe('<ResourceTemplateForm /> after fetching data from sinopia server', ()
...
-  it.skip('renders error alert box', async () => {
-    // FIXME: this test gives false positive - see github issue #496 - perhaps we need an integration test
-    // await wrapper.instance().fulfillRTPromises(promises).then(() => wrapper.update()).then(() => {
-    //   expect(wrapper.state.errot).toBeTruthy()
-    //   const errorEl = wrapper.find('div.alert')
-    //   expect(errorEl).toHaveLength(1)
-    //   expect(errorEl.text()).toEqual('Sinopia server is offline or has no resource templates to display')
-    // }).catch(e => {})
+
+  const asyncCall = () => {
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: whoops - another mockAsyncCall

File: __tests__/components/editor/ResourceTemplateForm.test.js [hunk 13]
```diff
@@ -305,31 +260,60 @@ describe('<ResourceTemplateForm /> after fetching data from sinopia server', ()
...
+          ]
+        }
+      }
+    ]
+  }
+
+  const wrapper = shallow(<ResourceTemplateForm {...rtProps} resourceTemplate = {rtTest}/>)
+
+  it('renders error alert box', async () => {
+    expect.assertions(3)
```
Comment (ndushay) [inline __tests__/components/editor/ResourceTemplateForm.test.js]: 🕺

File: src/components/editor/ResourceTemplateForm.jsx [hunk 14]
```diff
@@ -12,14 +12,12 @@ import PropertyResourceTemplate from './PropertyResourceTemplate'
 import lookupConfig from '../../../static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json'
 import { getLD, setItems, removeAllContent } from '../../actions/index'
 import { getResourceTemplate } from '../../sinopiaServer'
+import {resourceToName} from "../../Utilities";
```
Comment (ndushay) [inline src/components/editor/ResourceTemplateForm.jsx]: totally ok to ignore ... all other curly braces nearby have a space.  :-P

File: src/components/editor/ResourceTemplateForm.jsx [hunk 15]
```diff
@@ -85,7 +84,11 @@ export class ResourceTemplateForm extends Component {
 
   resourceTemplatePromises = async (templateRefs) => {
```
Comment (ndushay) [inline src/components/editor/ResourceTemplateForm.jsx]: so now this is returning a single promise, yes?   Would `resourceTemplatesPromise` be more accurate?

File: src/components/editor/ResourceTemplateForm.jsx [hunk 16]
```diff
@@ -222,7 +225,9 @@ export class ResourceTemplateForm extends Component {
     const errMessage = <div className="alert alert-warning">
       There are missing resource templates required by resource template: <strong>{this.props.resourceTemplate.resourceURI}</strong>.
       <br />
-      Make sure all referenced templates in property template are uploaded first
+      Please make sure all referenced templates in property template are uploaded first. Missing templates:
```
Comment (ndushay) [inline src/components/editor/ResourceTemplateForm.jsx]: 🕺

File: __tests__/components/editor/ResourceTemplateForm.test.js (hunk 10 above)
Comment (jgreben) [reply __tests__/components/editor/ResourceTemplateForm.test.js]: Yes, all it requires for the test is the resourceURI.

File: __tests__/components/editor/ResourceTemplateForm.test.js (hunk 12 above)
Comment (jgreben) [reply __tests__/components/editor/ResourceTemplateForm.test.js]: Fixed.

File: src/components/editor/ResourceTemplateForm.jsx (hunk 15 above)
Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: I don't think so...It's doing Promise.all and iterating over the collected resource templates that it found in the profile.

File: src/components/editor/ResourceTemplateForm.jsx (hunk 14 above)
Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: I guess people like spaces in their curly braces... :)

File: src/components/editor/ResourceTemplateForm.jsx (hunk 15 above)
Comment (ndushay) [reply src/components/editor/ResourceTemplateForm.jsx]: yes, but it returns a single promise (I had to look that up) for all of the templates combined.  Merging, but if you agree, feel free to make a tiny PR.

Comment (jgreben) [reply src/components/editor/ResourceTemplateForm.jsx]: ok that makes sense.
