### PR TITLE
Fixes typehead bug when hitting backspace key.

### LINKED ISSUE #581: Firefox only: hitting delete button in a QA lookup field to remove a value has same effect as browser back button
In Editor, in a lookup field that uses QA, when the user hits the "delete" key with the intention of backspacing to remove one of the previously selected values (or to remove the last typed character in a type ahead), it's as if you hit the browser back button. You are taken off of the cataloging screen and back to the list of Resource Templates.
[delete_key.swf.zip](https://github.com/LD4P/sinopia_editor/files/3234661/delete_key.swf.zip)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #581

So this isn't perfect (you have to hit backspace twice to delete a value in a typeahead box), but better than the reported bug.

### CODE REVIEW

File: src/components/editor/property/InputListLOC.jsx [hunk 1]
```diff
@@ -25,6 +25,17 @@ class InputListLOC extends Component {
     }
   }
 
+  // From https://github.com/ericgio/react-bootstrap-typeahead/issues/389
+  onKeyDown = (e) => {
```
Comment (jcoyne) [inline src/components/editor/property/InputListLOC.jsx]: Can this code be extracted and shared among all 3 components?

Comment (justinlittman) [reply src/components/editor/property/InputListLOC.jsx]: It could, but (1) these components need to be refactored in general to remove redundancy and (2) we don't share component action functions anywhere else, so this would be a one-off.

If you feel strongly, I will extract but otherwise my gut is to leave as is.

Comment (ndushay) [reply src/components/editor/property/InputListLOC.jsx]: I'm fine with it as is;  Sandi Metz told us:

- repeat code once -- hold your nose and do it
- repeat code twice - still hold your nose and do it, esp. if code has low churn
