### PR TITLE
Insert diacritics at the cursor's current position

### LINKED ISSUE #2097: DiacriticsSelection insert value at Input's cursor location
**Describe the bug**
What went wrong? What did you expect to happen?
When user enters values using the `DiacriticsSelection` component, the value is append at the end regardless of the user's cursor location.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
When user enters a quick string of characters and expects to go back and insert a character, they expect that the selection would be inserted into the cursor location. Workaround is only the characters up to the point of insertion, select character, and then continue data entry.

- What environment are you in? (stage or production)
both
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Mac/Firefox.

- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)
sinopia-bug-02020-03-06

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
Fixes #2097

### CODE REVIEW

File: src/components/editor/property/InputValue.jsx [hunk 1]
```diff
@@ -32,7 +32,6 @@ const InputValue = (props) => {
       </button>
     </div>
     <button
-      id="editItem"
```
Comment (jcoyne) [inline src/components/editor/property/InputValue.jsx:35]: This ID is not unique on the page.

**Review by jermnelson — APPROVED** [review]
