### PR TITLE
Fixes language input (you know, so that you can input a language) and…

### LINKED ISSUE #275: Setting Language for Input type literal: Hitting cancel should empty out the current redux store pertaining to that field.
- Could be related to #256
- If you want to cancel setting a language, make sure Cancel will remove or reset the redux store for that Input Literal field.

- Currently, when you add a field to a literal, then click on the language to update it, but hit cancel, the language still gets se in redux

### LINKED ISSUE #529: Fix displayLang in InputLiteral
The `InputLiteral` component's `displayLang` needs to update to the specific item object in Redux state.,

### PR DESCRIPTION
**Pull request by justinlittman**
… adds lang to state.

closes #529
closes #275

### CODE REVIEW

File: src/components/editor/InputLang.jsx [hunk 1]
```diff
@@ -15,47 +14,38 @@ class InputLang extends Component {
...
-        })
-
-        return { id: uri, uri, label }
-      } catch (error) {
-        // ignore
-      }
-    }
+    return json.reduce((result, item) => {
+      // Object.getOwnPropertyDescriptor is necessary to handle the @
+      const uri = Object.getOwnPropertyDescriptor(item, '@id').value
```
Comment (mjgiarlo) [inline src/components/editor/InputLang.jsx]: Can also use the safe navigation operator here, which we use in a couple other spots in the editor:

```javascript
const uri = item?.['@id'].value
```

I am not sure which is more idiomatic or more readable.

Comment (mjgiarlo) [reply src/components/editor/InputLang.jsx]: Or `item['@id']` if you don't need safe navigation.

File: src/components/editor/InputLang.jsx [hunk 2]
```diff
@@ -15,47 +14,38 @@ class InputLang extends Component {
...
+      const labelArrayDescr = Object.getOwnPropertyDescriptor(item, 'http://www.loc.gov/mads/rdf/v1#authoritativeLabel')
+      // There are some odd entries, so ignoring if don't have labels.
+      if (!labelArrayDescr) return result
+      const labelArray = labelArrayDescr.value
+
+      // Looking for English label
+      let label = null
+      labelArray.forEach((langItem) => {
+        if (langItem['@language'] == 'en') {
```
Comment (mjgiarlo) [inline src/components/editor/InputLang.jsx]: It would be better to get eslint to enforce this for us, but generally I think we should prefer `===` over `==` since the latter does type conversions. (Which can be useful if we want type conversions...)

File: src/reducers/inputs.js [hunk 3]
```diff
@@ -42,6 +42,31 @@ export const setMyItems = (state, action) => {
...
+  const reduxPath = action.payload.reduxPath
+  let level = 0
+
+  reduxPath.reduce((obj, key) => {
+    level++
+    if (level === reduxPath.length) {
+      if ((key in obj) != true) {
+        obj[key] = { items: [] }
+      }
+      obj[key].items.forEach(item => {
```
Comment (mjgiarlo) [inline src/reducers/inputs.js]: I wonder if this should use `map()` instead since you're modifying values in the array?

File: src/reducers/inputs.js [hunk 4]
```diff
@@ -42,6 +42,31 @@ export const setMyItems = (state, action) => {
...
+        if (item.id == action.payload.id) {
```
Comment (mjgiarlo) [inline src/reducers/inputs.js]: Is this only going to match one item in the array or multiple? (Not sure what this data tends to look like.) If only the first, we may want a different iterator function above.

File: src/reducers/inputs.js (hunk 3 above)
Comment (mjgiarlo) [reply src/reducers/inputs.js]: On second thought, no, I don't think `map()` is a good fit here since you're looking to mutate a single property in a single object in the array (I think?).

File: src/components/editor/InputLang.jsx (hunk 1 above)
Comment (justinlittman) [reply src/components/editor/InputLang.jsx]: Agree with you that these are more idiomatic. However, for some unknown reason they don't work with `@id`.

File: src/reducers/inputs.js (hunk 4 above)
Comment (justinlittman) [reply src/reducers/inputs.js]: Yes, only one. Open to suggestions.

File: src/components/editor/InputLang.jsx (hunk 1 above)
Comment (mjgiarlo) [reply src/components/editor/InputLang.jsx]: @justinlittman That's surprising! What kind of thing is `item` here? I created a dummy object in the console that contained a key of `@id` and it worked fine. So clearly you're not dealing with a dummy object here. :)

File: src/reducers/inputs.js (hunk 4 above)
Comment (mjgiarlo) [reply src/reducers/inputs.js]: OK, cool. How about:

```javascript
const payloadItem = obj[key].	items.find(item => item.id === action.payload.id)
payloadItem.lang = { items: action.payload.items }
```

Comment (justinlittman) [reply src/reducers/inputs.js]: Thanks for the suggestion. Updated.
