### PR TITLE
Make resource close button close the expected tab

### LINKED ISSUE #2057: Close and save buttons not closing/saving open tab
What went wrong? 
When saving, I get confirmation of the save but when closing am told that there is unsaved information. And, when clicking the Close button, the leftmost resource template is closed, not the one that is open.
What did you expect to happen?
I expect the RT that I am working on to save when I press the save button and close when I press the close button.

- What is the impact on your work? Really super annoying.
- What environment are you in? production
- What OS and browser are you using? Windows; Firefox
- If you're cataloging, what Resource Template were you using? UAL Monograph Opus (Un-Nested), UAL Monograph Work (Un-Nested), UAL Monograph Instance (Un-Nested) and UAL Monograph Item (Un-Nested)

**Please include a screenshot**
Snag_4b45a25

Snag_4b487bd

Snag_4b49e72

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #2057

## Why was this change made?

The prior implementation of CloseResourceModal used the selectCurrentResourceKey to figure out which resource the CloseButton should close, and that was the bug. Instead, the CloseButton should tell the CloseResourceModal what its resource is and it should close that resource.

## How was this change tested?

This change was tested in the browser and confirmed working. See linked screen capture:

Peek 2020-09-03 15-58

I briefly entertained the idea of adding unit tests for CloseButton and CloseResourceModal but it seemed of little value to test properties injection which is core React functionality. Given also that 1) such tests would not make it apparent that this bug is related to the tests, 2) my familiarity with React testing is relatively low, and 3) this is fixing a production bug, I decided not to add any automated tests in this commit. Happy to reconsider.

## Which documentation and/or configurations were updated?

None.

### CODE REVIEW

File: src/components/editor/actions/CloseResourceModal.jsx [hunk 1]
```diff
@@ -61,4 +60,8 @@ const CloseResourceModal = () => {
   return (<ModalWrapper modal={modal} />)
 }
 
+CloseResourceModal.propTypes = {
+  resourceKey: PropTypes.string,
```
Comment (justinlittman) [inline src/components/editor/actions/CloseResourceModal.jsx:64]: Can you add `isRequired`?

**Review by justinlittman — CHANGES_REQUESTED** [review]

File: src/components/editor/actions/CloseResourceModal.jsx (hunk 1 above)
Comment (mjgiarlo) [reply src/components/editor/actions/CloseResourceModal.jsx:64]: @justinlittman you bet.

**Comment by mjgiarlo** [comment]
@justinlittman have another look?

**Review by justinlittman — APPROVED** [review]
