### PR TITLE
Simplifying Reducers to fix blocking bug

### LINKED ISSUE #455: Resource Template reducers causing inconsistent Redux state
When a Resource Template is initially loaded,  the `setResourceTemplate` function is the function that loads, for example, the `resourceTemplate:bf2:Identifiers:Barcode` resource template for the **http://id.loc.gov/ontologies/bibframe/itemPortion** property with missing defaults:

Screen Shot 2019-04-17 at 10 41 37 AM
 the `resourceTemplate:bf2:Identifiers:Barcode` Resource Template has defaults that show-up by clicking through:
Screen Shot 2019-04-17 at 10 46 19 AM

Part of the problem is that the use of two different reducer functions; `setResourceTemplate` and `refreshResourceTemplate` that both create slightly different JSON shapes in the Redux store. Currently work on fix in the branch https://github.com/LD4P/sinopia_editor/tree/fix-repeatable-inputLiteral.

Blocks #387

### PR DESCRIPTION
**Pull request by jermnelson**
This PR fixes #455 by removing reselect caching (for now) and instead of creating two slightly different Redux shapes for the same resourceTemplate, the `setResourceTemplate` now calls the `refreshResourceTemplate` reducer. 

Switch to using shortids to store multiple resourceTemplates in Redux state, should make #346 easier to implement (i.e. when a resource is "repeatable", a new shortid and call to refreshResourceTemplate reducer adds a resourceTemplate to the existing property)

### CODE REVIEW

File: src/components/editor/InputLiteral.jsx [hunk 1]
```diff
@@ -223,6 +232,7 @@ InputLiteral.propTypes = {
 
 const mapStateToProps = (state, props) => {
   let result = getProperty(state, props)
+  if (result === undefined) result = []
```
Comment (mjgiarlo) [inline src/components/editor/InputLiteral.jsx]: Could this logic move into the `getProperty` definition? Something like:

```javascript
export const getProperty = createSelector(
  [ inputPropertySelector ],
  (propertyURI) => {
    return propertyURI.items || []
  }
)
```

:question:

File: src/reducers/index.js [hunk 2]
```diff
@@ -18,12 +16,13 @@ const inputPropertySelector = (state, props) => {
...
-  [ inputPropertySelector ],
-  (propertyURI) => {
-    return propertyURI.items
-  }
-)
+// TODO: Renable use of reselect's createSelector, will need to adjust
+// individual components InputLiteral, InputLookupQA, InputListLOC, etc.,
+// see https://github.com/reduxjs/reselect#sharing-selectors-with-props-across-multiple-component-instances
+export const getProperty = (state, props) => {
+  let result = inputPropertySelector(state, props)
```
Comment (mjgiarlo) [inline src/reducers/index.js]: I'm seeing both `let` and `const` used in this PR and other spots in the editor, and it's not clear to me what convention is being followed here. I've picked up generally that the conventional wisdom is to use `const` consistently except when you **know** you need a variable that will be mutated, in which case, use `let`.

File: src/reducers/index.js [hunk 3]
```diff
@@ -34,56 +33,58 @@ export const getAllRdf = (state, action) => {
...
   const lastKey = reduxPath.pop()
   const lastObject = reduxPath.reduce((newState, key) =>
       newState[key] = newState[key] || {},
-    newState)
+  newState)
   if (Object.keys(items).includes('items')) {
     lastObject[lastKey] = items
   } else {
-    lastObject[lastKey] = { items: items }
+    // lastObject[lastKey] = { items: items }
```
Comment (mjgiarlo) [inline src/reducers/index.js]: Worth leaving this around?

File: src/components/editor/PropertyResourceTemplate.jsx [hunk 4]
```diff
@@ -38,13 +38,15 @@ class PropertyResourceTemplate extends Component {
       <div>
       {
         this.props.resourceTemplate.propertyTemplates.map((property) => {
+          let keyId = shortid.generate()
           let newReduxPath = Object.assign([], this.props.reduxPath)
           newReduxPath.push(property.propertyURI)
+          newReduxPath.push(keyId)
```
Comment (mjgiarlo) [inline src/components/editor/PropertyResourceTemplate.jsx]: Is this covered by tests?

File: src/components/editor/PropertyTemplateOutline.jsx [hunk 5]
```diff
@@ -132,22 +132,13 @@ export class PropertyTemplateOutline extends Component {
...
-                payload['defaults'] = []
-                rtProperty.valueConstraint.defaults.map((row, i) => {
-                  payload['defaults'].push({
-                    id: i,
-                    content: row.defaultLiteral,
-                    uri: row.defaultURI
-                  })
-                })
-              }
+              const payload = { reduxPath: newReduxPath, property: rtProperty }
```
Comment (mjgiarlo) [inline src/components/editor/PropertyTemplateOutline.jsx]: Is this covered by tests?

File: src/components/editor/ResourceTemplateForm.jsx [hunk 6]
```diff
@@ -92,10 +92,12 @@ export class ResourceTemplateForm extends Component {
     rtIds.map((rtId, i) => {
       const rt = this.rtForPt(rtId)
       if (rt !== undefined) {
+        const keyId = shortid.generate()
+        const reduxPath = [this.props.rtId, propUri, keyId, rtId]
```
Comment (mjgiarlo) [inline src/components/editor/ResourceTemplateForm.jsx]: Is this covered by tests?

File: src/reducers/index.js (hunk 2 above)
Comment (jermnelson) [reply src/reducers/index.js]: That is my general practice as well to use `const` for immutable variables, changing this instance to a `let`.

File: src/reducers/index.js (hunk 3 above)
Comment (jermnelson) [reply src/reducers/index.js]: Good catch! Removing.

File: src/components/editor/InputLiteral.jsx (hunk 1 above)
Comment (jermnelson) [reply src/components/editor/InputLiteral.jsx]: Like your suggestion; updated in latest commit.

File: __tests__/reducers/index.test.js [hunk 7]
```diff
@@ -82,6 +83,7 @@ describe(`Takes a resource template ID and populates the global state`, () => {
   })
 
   it('handles SET_RESOURCE_TEMPLATE', () => {
+    const testId = jest.spyOn(shortid, 'generate').mockReturnValue(0)
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: this is set but never used.  Did you forget to add an expect statement, or did you forget to remove it?

File: __tests__/reducers/index.test.js [hunk 8]
```diff
@@ -94,15 +96,15 @@ describe(`Takes a resource template ID and populates the global state`, () => {
       { "authenticate": {"loginJwt": {}},
         "lang": {"formData": []},
         "selectorReducer": { 'resourceTemplate:bf2:Monograph:Instance':
-          { 'http://id.loc.gov/ontologies/bibframe/instanceOf': { 'resourceTemplate:bf2:Monograph:Work': {} },
+          { 'http://id.loc.gov/ontologies/bibframe/instanceOf': {},
             'http://id.loc.gov/ontologies/bibframe/issuance':
               { items:
-                [ { id: {},
+                [ { id: 0,
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: I assume it's ok for ids to crash across these arrays, but not within an array??

File: __tests__/reducers/index.test.js [hunk 9]
```diff
@@ -130,20 +132,88 @@ describe(`Takes a resource template ID and populates the global state`, () => {
...
-          items: [ "Sinopia Name" ]
+          items: [ {content: "Sinopia Name", id: 0, uri: undefined } ]
         }
       }
     })
   })
 
 })
+
+describe('Takes a property and returns an empty or a populated array', () => {
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: I think i would change this to ... `populateDefaults() method` as the tests enclosed seem to be testing that ...

File: __tests__/reducers/index.test.js [hunk 10]
```diff
@@ -130,20 +132,88 @@ describe(`Takes a resource template ID and populates the global state`, () => {
...
+
+  const propertyTemplate = {}
+
+  it('tests empty and undefined templates', () => {
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: `empty and undefined properties return empty array` ?

File: __tests__/reducers/index.test.js [hunk 11]
```diff
@@ -130,20 +132,88 @@ describe(`Takes a resource template ID and populates the global state`, () => {
...
+    const undefinedResult = populateDefaults()
+    expect(undefinedResult).toEqual([])
+    const nullResult = populateDefaults(null)
+    expect(nullResult).toEqual([])
+    const emptyObjectResult = populateDefaults({})
+    expect(emptyObjectResult).toEqual([])
+  })
+
+  it('tests a propertyTemplate without any defaults', () => {
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: `propertyTemplate without defaults returns empty array` ?

File: __tests__/reducers/index.test.js [hunk 12]
```diff
@@ -130,20 +132,88 @@ describe(`Takes a resource template ID and populates the global state`, () => {
...
+          "useValuesFrom": [],
+          "valueDataType": {}
+        },
+        "propertyURI": "http://id.loc.gov/ontologies/bibframe/identifiedBy",
+        "propertyLabel": "Call numbers"
+      })
+    expect(simpleProperty).toEqual([])
+  })
+
+  it('tests a propertyTemplate with defaults', () => {
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: `propertyTemplate with defaults returns array with object containg default values` ?

File: __tests__/reducers/index.test.js [hunk 13]
```diff
@@ -130,20 +132,88 @@ describe(`Takes a resource template ID and populates the global state`, () => {
   })
 
   it('tests with a more realistic payload with defaults', () => {
+    const testId = jest.spyOn(shortid, 'generate').mockReturnValue(0)
     const defaultStateResult = refreshResourceTemplate({}, {
       type: 'REFRESH_RESOURCE_TEMPLATE',
       payload: {
         reduxPath: ['resourceTemplate:bf2:Item', 'http://schema.org/name'],
-        defaults: ['Sinopia Name']
+        property: { valueConstraint: { defaults: [ { defaultLiteral: 'Sinopia Name' } ] }}
```
Comment (ndushay) [inline __tests__/reducers/index.test.js]: yes!  this is what the data should actually look like!

File: __tests__/reducers/literal.test.js [hunk 14]
```diff
@@ -23,6 +23,81 @@ describe('literal reducer functions', () => {
...
+     expect(emptyState).toEqual({
+       "resourceTemplate:Monograph:Instance": {
+         'http://schema.org/name': {
+           items: [{ id: 0, content: 'Run the tests'}]
+         }
+       }
+     })
+  })
+
+  it('SET_ITEMS adds item to populated state', () => {
```
Comment (ndushay) [inline __tests__/reducers/literal.test.js]: `appends` instead of `add`?

File: __tests__/reducers/literal.test.js [hunk 15]
```diff
@@ -23,6 +23,81 @@ describe('literal reducer functions', () => {
...
+    ).toEqual({
+       "resourceTemplate:Book": {},
+      'resourceTemplate:Monograph:Instance': {
+        "http://schema.org/description": {
+          items: [{ id: 2, content: "add this!"}]}
+      }
+    })
+  })
+
+  it('SET_ITEMS creates intermediate objects in state if present in reduxPath', () => {
```
Comment (ndushay) [inline __tests__/reducers/literal.test.js]: I don't understand this description, but maybe that's ok.

File: src/components/editor/InputLiteral.jsx [hunk 16]
```diff
@@ -23,6 +23,15 @@ export class InputLiteral extends Component {
     }
   }
 
+  componentDidMount = () => {
+    if (this.props.propertyTemplate.repeatable === "false" &&
+        this.props.formData !== undefined &&
+        this.props.formData.items.length > 0) {
+      this.setState( { disabled: true })
```
Comment (ndushay) [inline src/components/editor/InputLiteral.jsx]: is there a way to test this?  It's sorta what you're actually fixing ... seems worth having a test to show if we break it in future ...

File: src/reducers/index.js [hunk 17]
```diff
@@ -34,56 +33,58 @@ export const getAllRdf = (state, action) => {
...
   let newState = Object.assign({}, state)
   const reduxPath = action.payload.reduxPath
+  const propertyTemplate = action.payload.property
   if (reduxPath === undefined || reduxPath.length < 1) {
     return newState
   }
-  const items = action.payload.defaults || { items: [] }
+  const defaults = populateDefaults(propertyTemplate)
+
+  const items =  defaults.length > 0 ? { items: defaults } : {}
```
[the remark this answers is not in the document]
Comment (jermnelson) [reply src/reducers/index.js]: Setting an `items` property for all types of `propertyTemplates` resulted in the Redux state having empty an `item` array when the propertyTemplate was a resource.

File: __tests__/reducers/literal.test.js (hunk 15 above)
Comment (jermnelson) [reply __tests__/reducers/literal.test.js]: Since we're not actually initializing the Redux state for embedded resource templates until the `PropertyTemplateOutline` is expanded and data is entered in an included component like InputLiteral, we need to create these intermediate objects if they don't exist.

File: src/components/editor/InputLiteral.jsx (hunk 16 above)
Comment (jermnelson) [reply src/components/editor/InputLiteral.jsx]: Done in latest commit

File: src/components/editor/PropertyResourceTemplate.jsx (hunk 4 above)
Comment (jermnelson) [reply src/components/editor/PropertyResourceTemplate.jsx]: Yes, `PropertyTemplateOutline` now has a test for Redux Path.

File: src/components/editor/PropertyTemplateOutline.jsx (hunk 5 above)
Comment (jermnelson) [reply src/components/editor/PropertyTemplateOutline.jsx]: Now testing reduxPath for `resource`

File: src/components/editor/ResourceTemplateForm.jsx (hunk 6 above)
Comment (jermnelson) [reply src/components/editor/ResourceTemplateForm.jsx]: Tests now added.

File: src/reducers/index.js [hunk 18]
```diff
@@ -18,12 +16,13 @@ const inputPropertySelector = (state, props) => {
...
-  (propertyURI) => {
-    return propertyURI.items
-  }
-)
+// TODO: Renable use of reselect's createSelector, will need to adjust
+// individual components InputLiteral, InputLookupQA, InputListLOC, etc.,
+// see https://github.com/reduxjs/reselect#sharing-selectors-with-props-across-multiple-component-instances
+export const getProperty = (state, props) => {
+  let result = inputPropertySelector(state, props)
+  return result.items
```
[the remark this answers is not in the document]
Comment (jermnelson) [reply src/reducers/index.js]: I like keeping this as is because we'll need this form when we re-enable reselect for `getProperty`.

File: __tests__/reducers/index.test.js (hunk 12 above)
Comment (jermnelson) [reply __tests__/reducers/index.test.js]: Now changed.

File: src/reducers/index.js [hunk 19]
```diff
@@ -34,56 +33,58 @@ export const getAllRdf = (state, action) => {
   return output.selectorReducer
 }
 
+export const populateDefaults = (propertyTemplate) => {
```
[the remark this answers is not in the document]
Comment (jermnelson) [reply src/reducers/index.js]: Done.

File: __tests__/reducers/index.test.js (hunk 8 above)
Comment (jermnelson) [reply __tests__/reducers/index.test.js]: Yes, keys only need to be unique within the context of the Javascript object; they won't clash across different arrays.

File: __tests__/reducers/index.test.js (hunk 10 above)
Comment (jermnelson) [reply __tests__/reducers/index.test.js]: Now changed.

File: __tests__/reducers/index.test.js (hunk 11 above)
Comment (jermnelson) [reply __tests__/reducers/index.test.js]: Now changed.

File: __tests__/reducers/index.test.js (hunk 9 above)
Comment (jermnelson) [reply __tests__/reducers/index.test.js]: Now changed.

**Comment by jermnelson** [comment]
> I'm still not clear on how you are testing new ComponentDidMount code in InputLiteral, but 🤷‍♀

On line [287](https://github.com/LD4P/sinopia_editor/pull/493/files#diff-dd4abf0074056200f6725d7ccb584b38R287) tests the class that is being set in `componentDidMount` function. For the `InputLiteral` logic, it doesn't matter if the **formData** is set in Redux or as an explicit prop as I did in the test.
