### PR TITLE
minimal integration test passes and some additional build refactors

### LINKED ISSUE #16: test doing something and passing in CI
#3 hooks up CI, but we currently have a failing test or no-op test.  Let's make it pass!

Note:  may involve:
- jest-puppeteer
- grunt work so all the code needed to run the editor is in a single directory (sort of "deploy"-like)

### LINKED ISSUE #29: use jest-puppeteer for integration tests
Exemplars:
- https://github.com/ProjectMirador/research-and-demos/tree/master/minimal_redux_poc (Uses webpack, jest, puppeteer, react, enzyme)
- https://github.com/UniversalViewer/universalviewer (Uses grunt + jest + puppeteer)

### PR DESCRIPTION
**Pull request by ndushay**
There are a bunch of commits here, but I think you can review everything in one shot (rather than commit by commit).  

If you would find it easier, I am happy to split this into two PRs, one about build refactoring and one about getting our first integration test with puppeteer.   I would also be happy to squash commits or whatever would make it easier for you or better for the commit history.

The changes are basically:

- created a minimal integration test using puppeteer and got it to pass locally and with circleci

Also
- grunt cleans out the build dir before running the build
- copy static/js files mentioned in index.html to builds dir and use those files
- removed static/js/lodash.js file as it wasn't used
- removed a grunt subtask that never did anything

Closes #16 (test does something)
closes #29 (use jest-puppeteer)

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -18,6 +26,21 @@ module.exports = function(grunt) {
         stripBanners: true,
         banner: '/* <%= pkg.name %> <%= grunt.template.today("yyyy-mm-dd") %> */',
       },
+      static_mappings: {
```
Comment (jermnelson) [inline Gruntfile.js]: I like this approach to a cleaner builds directory

File: __tests__/integration/basic.test.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+describe('Basic end to end Sinopia BIBFRAME Editor', () => {
+  beforeAll(async () => {
+    await page.goto('http://127.0.0.1:8000/');
+  });
+
+  it('displays "Bibframe Editor Workspace" text', async () => {
```
Comment (jermnelson) [inline __tests__/integration/basic.test.js]: So I'm getting an error that this text is not found. If you run the `node server-bfe.js`, you get the following display that is missing this text.

screen shot 2018-10-02 at 10 20 49 am

File: Gruntfile.js [hunk 3]
```diff
@@ -18,6 +26,21 @@ module.exports = function(grunt) {
...
+        files: [
+          // note:  also need index.html, static/css and static/images files
+          {src: 'server-bfe.js', dest: 'builds/server-bfe.js'},
+          {src: 'static/js/config.js', dest: 'builds/config.js'},
+          {src: 'static/js/jsonld-vis.js', dest: 'builds/jsonld-vis.js'},
```
[the remark this answers is not in the document]
Comment (ndushay) [reply Gruntfile.js]: I made ticket #30 re: running it entirely from a builds (or dist) directory, #28 about using webpack instead of grunt.  I will add to #28 re: redoing directory organization.   

It seems better, to me, to get some basic integration tests written before doing any of that as it will help us know if we've done it correctly.

File: Gruntfile.js (hunk 1 above)
Comment (ndushay) [reply Gruntfile.js]: yeah, it really bugged me to be using stuff outside of a builds or dist directory.  Ticket #30 captures running it entirely from a builds or dist directory.

File: __tests__/integration/basic.test.js (hunk 2 above)
Comment (ndushay) [reply __tests__/integration/basic.test.js]: ah - whoops.  Probably something I changed in index.html.  Will investigate now.

(but ... the TEST passed!)

Comment (ndushay) [reply __tests__/integration/basic.test.js]: Mine looks ok.  Did you npm install and grunt first?

image

File: Gruntfile.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (jgreben) [reply Gruntfile.js]: 👍

**Comment by jgreben** [comment]
LGTM 👍
